export default [
	{
		name: "Stick",
		power: 10,
		cost: 10,
		description: "A simple wooden stick.",
		special: "Critical",
	},
	{
		name: "Dagger",
		power: 20,
		cost: 40,
		description: "A sharp, small blade for quick strikes.",
		special: "Critical",
	},
	{
		name: "Claw hammer",
		power: 40,
		cost: 90,
		description: "A versatile hammer with a claw for pulling and smashing.",
		special: null,
	},
	{
		name: "Sword",
		power: 70,
		cost: 130,
		description: "A standard sword for balanced offense and defense.",
		special: null,
	},
	{
		name: "Shortbow",
		power: 35,
		cost: 160,
		description: "A compact bow for ranged attacks.",
		special: "Double Shot",
	},
	{
		name: "Rapier",
		power: 50,
		cost: 200,
		description: "A slender, quick sword for precise thrusts.",
		special: "Critical Thrust",
	},
	{
		name: "Crossbow",
		power: 60,
		cost: 240,
		description: "A powerful crossbow for accurate shots.",
		special: "Piercing Shot",
	},
	{
		name: "Longbow",
		power: 45,
		cost: 280,
		description: "A longer bow for increased range and power.",
		special: "Sniper Shot",
	},
	{
		name: "Spear",
		power: 80,
		cost: 320,
		description: "A polearm with a pointed tip for thrusting attacks.",
		special: "Impale",
	},
	{
		name: "Flail",
		power: 75,
		cost: 360,
		description: "A chain weapon with a spiked ball for unpredictable swings.",
		special: "Whirlwind",
	},
	{
		name: "Mace",
		power: 90,
		cost: 400,
		description: "A heavy club with a spiked head for crushing blows.",
		special: null,
	},
	{
		name: "War axe",
		power: 110,
		cost: 440,
		description: "A double-edged axe for powerful chopping attacks.",
		special: null,
	},
	{
		name: "Katana",
		power: 100,
		cost: 480,
		description: "A razor-sharp, single-edged sword for deadly slashes.",
		special: null,
	},
	{
		name: "Warhammer",
		power: 120,
		cost: 520,
		description: "A massive hammer for devastating, armor-piercing strikes.",
		special: null,
	},
	{
		name: "Battleaxe",
		power: 130,
		cost: 560,
		description:
			"A heavy axe with a broad cutting edge for cleaving through enemies.",
		special: "Cleave",
	},
	{
		name: "Halberd",
		power: 140,
		cost: 600,
		description:
			"A polearm with an axe blade, spear point, and hook for versatile attacks.",
		special: "Versatile Strikes",
	},
	{
		name: "Greatsword",
		power: 160,
		cost: 640,
		description: "A massive two-handed sword for overwhelming strikes.",
		special: null,
	},
	{
		name: "Giant War Maul",
		power: 180,
		cost: 680,
		description: "An enormous, brutal maul for smashing through defenses.",
		special: "Smash",
	},
	{
		name: "Executioner's Guillotine",
		power: 200,
		cost: 720,
		description: "A massive, intimidating axe with a guillotine-like blade.",
		special: "Decapitate",
	},
	{
		name: "Vorpal Dagger",
		power: 220,
		cost: 760,
		description: "A magical dagger with a razor-sharp edge.",
		special: "Teleport Strike",
	},
	{
		name: "Enchanted Longbow",
		power: 210,
		cost: 800,
		description: "A longbow infused with mystical energy for enhanced shots.",
		special: "Arcane Shot",
	},
	{
		name: "Thunderclap Mace",
		power: 230,
		cost: 840,
		description: "A mace that unleashes thunderous shockwaves on impact.",
		special: "Thunder Strike",
	},
	{
		name: "Firebrand Sword",
		power: 250,
		cost: 880,
		description: "A sword imbued with the power of fire for scorching attacks.",
		special: "Inferno Slash",
	},
	{
		name: "Iceforged Spear",
		power: 270,
		cost: 920,
		description: "A spear crafted from enchanted ice for freezing thrusts.",
		special: "Frost Pierce",
	},
	{
		name: "Dragon Slayer",
		power: 300,
		cost: 960,
		description: "A legendary sword forged from the scales of a slain dragon.",
		special: "Dragon's Fury",
	},
];
