export default [
	{
		name: "stick",
		power: 5,
		cost: 5,
		description: "A simple wooden stick.",
		special: null,
	},
	{
		name: "dagger",
		power: 20,
		cost: 15,
		description: "A sharp, small blade for quick strikes.",
		special: null,
	},
	{
		name: "claw hammer",
		power: 40,
		cost: 30,
		description: "A versatile hammer with a claw for pulling and smashing.",
		special: null,
	},
	{
		name: "sword",
		power: 70,
		cost: 50,
		description: "A standard sword for balanced offense and defense.",
		special: null,
	},
	{
		name: "shortbow",
		power: 35,
		cost: 40,
		description: "A compact bow for ranged attacks.",
		special: "Double Shot",
	},
	{
		name: "crossbow",
		power: 60,
		cost: 55,
		description: "A powerful crossbow for accurate shots.",
		special: "Piercing Shot",
	},
	{
		name: "rapier",
		power: 50,
		cost: 45,
		description: "A slender, quick sword for precise thrusts.",
		special: "Critical Thrust",
	},
	{
		name: "longbow",
		power: 45,
		cost: 50,
		description: "A longer bow for increased range and power.",
		special: "Sniper Shot",
	},
	{
		name: "spear",
		power: 80,
		cost: 65,
		description: "A polearm with a pointed tip for thrusting attacks.",
		special: "Impale",
	},
	{
		name: "flail",
		power: 75,
		cost: 70,
		description: "A chain weapon with a spiked ball for unpredictable swings.",
		special: "Whirlwind",
	},
	{
		name: "mace",
		power: 90,
		cost: 80,
		description: "A heavy club with a spiked head for crushing blows.",
		special: null,
	},
	{
		name: "whip",
		power: 55,
		cost: 60,
		description:
			"A flexible weapon with a long reach, ideal for disarming foes.",
		special: "Disarm",
	},
	{
		name: "war axe",
		power: 110,
		cost: 95,
		description: "A double-edged axe for powerful chopping attacks.",
		special: null,
	},
	{
		name: "katana",
		power: 100,
		cost: 90,
		description: "A razor-sharp, single-edged sword for deadly slashes.",
		special: null,
	},
	{
		name: "warhammer",
		power: 120,
		cost: 105,
		description: "A massive hammer for devastating, armor-piercing strikes.",
		special: null,
	},
	{
		name: "battleaxe",
		power: 130,
		cost: 110,
		description:
			"A heavy axe with a broad cutting edge for cleaving through enemies.",
		special: "Cleave",
	},
	{
		name: "halberd",
		power: 140,
		cost: 120,
		description:
			"A polearm with an axe blade, spear point, and hook for versatile attacks.",
		special: "Versatile Strikes",
	},
	{
		name: "greatsword",
		power: 160,
		cost: 135,
		description: "A massive two-handed sword for overwhelming strikes.",
		special: null,
	},
	{
		name: "giant war maul",
		power: 180,
		cost: 150,
		description: "An enormous, brutal maul for smashing through defenses.",
		special: "Smash",
	},
	{
		name: "executioner's guillotine",
		power: 200,
		cost: 170,
		description: "A massive, intimidating axe with a guillotine-like blade.",
		special: "Decapitate",
	},
];
