export default [
	{
		name: "Stick",
		power: 5,
		cost: 5,
		description: "A simple wooden stick.",
		special: null,
	},
	{
		name: "Dagger",
		power: 20,
		cost: 15,
		description: "A sharp, small blade for quick strikes.",
		special: null,
	},
	{
		name: "Claw hammer",
		power: 40,
		cost: 30,
		description: "A versatile hammer with a claw for pulling and smashing.",
		special: null,
	},
	{
		name: "Sword",
		power: 70,
		cost: 50,
		description: "A standard sword for balanced offense and defense.",
		special: null,
	},
	{
		name: "Shortbow",
		power: 35,
		cost: 40,
		description: "A compact bow for ranged attacks.",
		special: "Double Shot",
	},
	{
		name: "Crossbow",
		power: 60,
		cost: 55,
		description: "A powerful crossbow for accurate shots.",
		special: "Piercing Shot",
	},
	{
		name: "Rapier",
		power: 50,
		cost: 45,
		description: "A slender, quick sword for precise thrusts.",
		special: "Critical Thrust",
	},
	{
		name: "Longbow",
		power: 45,
		cost: 50,
		description: "A longer bow for increased range and power.",
		special: "Sniper Shot",
	},
	{
		name: "Spear",
		power: 80,
		cost: 65,
		description: "A polearm with a pointed tip for thrusting attacks.",
		special: "Impale",
	},
	{
		name: "Flail",
		power: 75,
		cost: 70,
		description: "A chain weapon with a spiked ball for unpredictable swings.",
		special: "Whirlwind",
	},
	{
		name: "Mace",
		power: 90,
		cost: 80,
		description: "A heavy club with a spiked head for crushing blows.",
		special: null,
	},
	{
		name: "Whip",
		power: 55,
		cost: 60,
		description:
			"A flexible weapon with a long reach, ideal for disarming foes.",
		special: "Disarm",
	},
	{
		name: "War axe",
		power: 110,
		cost: 95,
		description: "A double-edged axe for powerful chopping attacks.",
		special: null,
	},
	{
		name: "Katana",
		power: 100,
		cost: 90,
		description: "A razor-sharp, single-edged sword for deadly slashes.",
		special: null,
	},
	{
		name: "Warhammer",
		power: 120,
		cost: 105,
		description: "A massive hammer for devastating, armor-piercing strikes.",
		special: null,
	},
	{
		name: "Battleaxe",
		power: 130,
		cost: 110,
		description:
			"A heavy axe with a broad cutting edge for cleaving through enemies.",
		special: "Cleave",
	},
	{
		name: "Halberd",
		power: 140,
		cost: 120,
		description:
			"A polearm with an axe blade, spear point, and hook for versatile attacks.",
		special: "Versatile Strikes",
	},
	{
		name: "Greatsword",
		power: 160,
		cost: 135,
		description: "A massive two-handed sword for overwhelming strikes.",
		special: null,
	},
	{
		name: "Giant War Maul",
		power: 180,
		cost: 150,
		description: "An enormous, brutal maul for smashing through defenses.",
		special: "Smash",
	},
	{
		name: "Executioner's Guillotine",
		power: 200,
		cost: 170,
		description: "A massive, intimidating axe with a guillotine-like blade.",
		special: "Decapitate",
	},
	{
		name: "Dragon Slayer",
		power: 250,
		cost: 350,
		description: "A legendary sword forged from the scales of a slain dragon.",
		special: "Dragon's Bane",
	},
];
